all:
  children:
    ec2_instances:
      hosts:
        16.170.208.235:
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/managed_node1.pem
        # 13.60.170.175:
        #   ansible_user: ubuntu
        #   ansible_ssh_private_key_file: ~/.ssh/managed_node2.pem
